name: "Hellow World"

on: [pull_request]

jobs:
  sample:
    name: Hello World Job
    runs-on: ubuntu-latest
    steps:
      name: display
      run: echo "Hello World !!!!"
      
      name: hobby
      run: echo "my hobby is tennis!!"
    
    steps:
      name: aaa
      run: echo "hello"